#!lua
-- enqueue.lua: add one job to the stream, deduplicating by an optional idempotency key.
--
-- The `#!lua` shebang (no flags) makes Redis check for OOM *before* the script runs, so
-- under `noeviction` a full Redis rejects the whole script instead of failing halfway.
--
-- KEYS[1]   stream
-- KEYS[2]   idem key (present only when the producer supplied an idempotency key)
-- ARGV[1]   job_id (generated by the client, UUIDv7)
-- ARGV[2]   idempotency TTL in seconds (unused without KEYS[2])
-- ARGV[3..] job fields as alternating name, value (Job.to_fields)
--
-- Returns {job_id, created}. created = 1 if this call added a stream entry; 0 if an
-- earlier enqueue with the same idempotency key already did, in which case job_id is
-- the ORIGINAL job's id, not ARGV[1].
--
-- Re-send after a lost reply (ADR-006): with an idempotency key, the re-send finds the
-- key and returns the original id. Without one, it adds a second entry with the same
-- job_id, and commit.lua suppresses whichever copy finishes second.

local job_id = ARGV[1]

if KEYS[2] then
  -- SET NX succeeds only for the first enqueue with this key; EX bounds the dedup window.
  local claimed = redis.call('SET', KEYS[2], job_id, 'NX', 'EX', ARGV[2])
  if not claimed then
    -- Someone got here first: hand back their job_id and add nothing.
    -- (Keys can't expire mid-script, so this GET sees the key SET NX just saw.)
    return {redis.call('GET', KEYS[2]), 0}
  end
end

-- Stamp the enqueue time from Redis's clock, not the producer's: every latency number
-- is then a difference of two readings of the same clock (ADR-020).
local t = redis.call('TIME')                                        -- {seconds, microseconds}
local now_ms = string.format('%d', t[1] * 1000 + math.floor(t[2] / 1000))

-- Copy the caller's field/value pairs and append the timestamp.
local fields = {}
for i = 3, #ARGV do
  fields[#fields + 1] = ARGV[i]
end
fields[#fields + 1] = 'enqueued_at_ms'
fields[#fields + 1] = now_ms

-- '*' lets Redis pick a monotonically increasing entry id.
redis.call('XADD', KEYS[1], '*', unpack(fields))

return {job_id, 1}
