#!lua
-- enqueue.lua: admit one job to the queue, or refuse it because the queue is full
-- (backpressure, ADR-031), deduplicating by an optional idempotency key.
--
-- The `#!lua` shebang (no flags) makes Redis check for OOM *before* the script runs, so
-- under `noeviction` a full Redis rejects the whole script instead of failing halfway.
--
-- KEYS[1]   stream
-- KEYS[2]   delayed set (retries waiting for their backoff; part of the queue's depth)
-- KEYS[3]   "full" flag (backpressure hysteresis state)
-- KEYS[4]   stats hash
-- KEYS[5]   idem key (present only when the producer supplied an idempotency key)
-- ARGV[1]   job_id (generated by the client, UUIDv7)
-- ARGV[2]   idempotency TTL in seconds (unused without KEYS[5])
-- ARGV[3]   high watermark: at this depth the queue becomes full
-- ARGV[4]   low watermark: once full, it stays full until depth falls below this
-- ARGV[5]   what to count if refused: 'rejected', 'blocked', or 'none' (a re-poll)
-- ARGV[6..] job fields as alternating name, value (Job.to_fields)
--
-- Returns {job_id, status, depth}:
--   status  1  ADDED: a new stream entry; depth is the queue depth after adding it
--   status  0  DUPLICATE: an earlier enqueue with this idempotency key already added
--              the job; job_id is that ORIGINAL id and nothing was added
--   status -1  FULL: refused, nothing was written except the counter; job_id is ''
--
-- Why the check lives here and not in the client: the check and the XADD are one
-- atomic step, so no number of concurrent producers can push the depth past the high
-- watermark (enqueue never adds at depth >= high). A client-side check against a
-- cached depth would let every producer overshoot by whatever it sent while its cache
-- was stale. XLEN and ZCARD are O(1), and this costs no extra round trip.
--
-- Re-send after a lost reply (ADR-006): with an idempotency key, the re-send finds the
-- key and returns the original id. Without one, it adds a second entry with the same
-- job_id, and commit.lua suppresses whichever copy finishes second.

local job_id = ARGV[1]

-- 1. A repeat of an enqueue that was already accepted adds nothing, so it is answered
--    even when the queue is full: the producer learns its job exists.
if KEYS[5] then
  local original = redis.call('GET', KEYS[5])
  if original then
    return {original, 0, -1}
  end
end

-- 2. Admission. Depth = undelivered + in flight (XLEN: every exit XDELs, ADR-016) +
--    retries waiting for their backoff (they will come back, ADR-026).
local depth = redis.call('XLEN', KEYS[1]) + redis.call('ZCARD', KEYS[2])
local high = tonumber(ARGV[3])
local low = tonumber(ARGV[4])
local full = redis.call('EXISTS', KEYS[3]) == 1
if full and depth < low then
  redis.call('DEL', KEYS[3])                                       -- drained enough: open
  full = false
elseif not full and depth >= high then
  redis.call('SET', KEYS[3], '1')                                  -- hit the top: close
  full = true
end
-- Hysteresis: between low and high the answer depends on which way we came from.
-- Without it, a queue hovering at the watermark would flip between full and not full
-- on every enqueue, and producers would see alternating accept/reject.
if full then
  if ARGV[5] ~= 'none' then
    redis.call('HINCRBY', KEYS[4], ARGV[5], 1)
  end
  return {'', -1, depth}
end

-- 3. Claim the idempotency key. Step 1 saw it absent in this same atomic script, so
--    this SET NX succeeds; EX bounds the dedup window.
if KEYS[5] then
  redis.call('SET', KEYS[5], job_id, 'NX', 'EX', ARGV[2])
end

-- 4. Stamp the enqueue time from Redis's clock, not the producer's: every latency number
--    is then a difference of two readings of the same clock (ADR-020).
local t = redis.call('TIME')                                        -- {seconds, microseconds}
local now_ms = string.format('%d', t[1] * 1000 + math.floor(t[2] / 1000))

-- Copy the caller's field/value pairs and append the timestamp.
local fields = {}
for i = 6, #ARGV do
  fields[#fields + 1] = ARGV[i]
end
fields[#fields + 1] = 'enqueued_at_ms'
fields[#fields + 1] = now_ms

-- '*' lets Redis pick a monotonically increasing entry id.
redis.call('XADD', KEYS[1], '*', unpack(fields))

return {job_id, 1, depth + 1}
